# Generated by Django 5.2 on 2025-04-20 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_category_id_photo_likes_count_photo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='likes_count',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
            ],
            options={
                'unique_together': {('photo', 'ip_address')},
            },
        ),
    ]
