# Generated by Django 5.2 on 2025-04-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_like_unique_together_like_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('photo', 'ip_address')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
